### ISSUE TITLE
Meetup Cards

### ISSUE THREAD

**Issue by caseywatts** [techcorridorio/techcorridorio.github.io#2]
~brainstorming~ how to make a meeup card component that could be easily reusable on other groups' sites as well
- simple css markup = card style = `panel` from twitter bootstrap?
- simple templating = using a javascript template language (mustache?)
- simple meetup API interface
  - the API interface may be simple enough already, or maybe we want to wrap it some ourselves to expose just what we need easily
  - can we safely expose the api key to clients? we probably won't have a server between us and meetup
  - how can we include the meetup api js stuff most easily (maybe directly in the module in a script tag or maybe just at the top as a dependency like normal)

**Comment by benjaminoakes** [comment]
We should take some time to work on this together sometime.  :smile:

**Comment by caseywatts** [comment]
oops! I should've added the details in issue #3 here instead. I thought this one was about a more general topic, not just about meetup events.

I'll close this one as a duplicate.
