### ISSUE TITLE
Switch to HuBoard

### ISSUE THREAD

**Issue by benjaminoakes** [techcorridorio/techcorridorio.github.io#21]
I'd prefer to use [HuBoard](https://huboard.com/) over waffle.io because HuBoard is built by at least one local techie (@dahlbyk).  The intent is to use this to teach agile and also GitHub concepts to newbies, as well as just being a good tool for organizing the future of [techcorridor.io](http://techcorridor.io).
## Acceptance Criteria
- [x] Public HuBoard for techcorridor.io (Done! [Here it is.](https://huboard.com/techcorridorio/techcorridorio.github.io))
- [x] Add HuBoard badge to README (or, if one isn't available, link to [the HuBoard itself](https://huboard.com/techcorridorio/techcorridorio.github.io))
  - See also: https://github.com/huboard/huboard/issues/271
- [x] Remove waffle.io badge from README
- [x] Remove waffle.io labels from [GitHub](https://github.com/techcorridorio/techcorridorio.github.io/labels)

**Comment by benjaminoakes** [comment]
@dahlbyk I'd love to get your help on this!

**Comment by dahlbyk** [comment]
Glad to see the switch! Would love any and all feedback from those using the tool.

FYI, I remove the default WIP limit from the Working column to simplify things a bit.

**Comment by benjaminoakes** [comment]
> FYI, I remove the default WIP limit from the Working column to simplify things a bit.

Sounds good.
